name: Run API tests
on: [push, workflow_dispatch]
jobs:
  cypress-run:
    runs-on: macos-latest
    # strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving Cypress Cloud hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      # fail-fast: false
      # matrix:
      #   # run 3 copies of the current job in parallel
      #   containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # record: false
          # parallel: false
          # group: "Chrome"
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: "http://localhost:3001"
        # env:
        #   # pass GitHub token to allow accurately detecting a build vs a re-run build
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   # pass the Cypress Cloud record key as an environment variable
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        #   # pass the project ID from the secrets through environment variable
        #   CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
